# Generated by Django 4.2.26 on 2025-11-10 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseprofile',
            name='mobile_number',
        ),
    ]
