# Generated by Django 4.2.26 on 2025-11-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekerapp', '0002_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
