# Generated by Django 4.2.26 on 2025-11-10 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekerapp', '0003_jobseeker_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseeker',
            old_name='user',
            new_name='users',
        ),
    ]
