# Generated by Django 4.2.26 on 2025-11-10 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('poster', models.ImageField(upload_to='job pic')),
                ('posting_date', models.DateTimeField(auto_now_add=True)),
                ('last_date', models.DateField()),
                ('requirements', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approved'), ('Disapprove', 'Disapproved')], default='Pending', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companyapp.employer')),
            ],
        ),
    ]
