# Generated by Django 4.2.26 on 2025-11-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0003_employer_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='website',
            field=models.URLField(),
        ),
    ]
